name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  APP_ENV: testing
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: furima_test
  DB_USERNAME: root
  DB_PASSWORD: root

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: furima_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    strategy:
      matrix:
        php-version: [8.0, 8.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, dom, fileinfo, mysql, pdo_mysql
          coverage: none

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ./src/vendor
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('src/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-

      - name: Install dependencies
        working-directory: ./src
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Create environment file
        working-directory: ./src
        run: |
          echo "APP_NAME=Furima" > .env
          echo "APP_ENV=testing" >> .env
          echo "APP_KEY=" >> .env
          echo "APP_DEBUG=true" >> .env
          echo "APP_URL=http://localhost" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=furima_test" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env
          echo "CACHE_DRIVER=array" >> .env
          echo "SESSION_DRIVER=array" >> .env
          echo "QUEUE_CONNECTION=sync" >> .env
          echo "MAIL_MAILER=array" >> .env

      - name: Generate application key
        working-directory: ./src
        run: php artisan key:generate

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h"127.0.0.1" -P"3306" -u"root" -p"root" --silent; do
            echo 'Waiting for MySQL...'
            sleep 2
          done

      - name: Run migrations
        working-directory: ./src
        run: php artisan migrate --force

      - name: Run PHPStan
        working-directory: ./src
        run: composer analyse

      - name: Run PHP CS Check
        working-directory: ./src
        run: composer cs-check

      - name: Run Tests
        working-directory: ./src
        run: composer test

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: mbstring, dom, fileinfo

      - name: Install dependencies
        working-directory: ./src
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run security audit
        working-directory: ./src
        run: composer audit || true
